title: Ninja Quates # あなたのサイトのタイトルに置き換えてください
description: Gemini AIが自動生成した日々の格言ブログ # あなたのサイトの説明文に置き換えてください
# theme: minima # オプション: 人気のあるJekyllテーマ。最初はコメントアウトしておき、後で有効にできます。

# _postsフォルダ内のMarkdownファイルにデフォルトでpostレイアウトを適用
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
